---
kind: pipeline
name: amd64-latest

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: latest
    dockerfile: latest/Dockerfile.amd64
    dry_run: true
    repo: webhippie/unifi
    tags: latest-amd64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: latest
    dockerfile: latest/Dockerfile.amd64
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: latest-amd64
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: arm32v6-latest

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: latest
    dockerfile: latest/Dockerfile.arm32v6
    dry_run: true
    repo: webhippie/unifi
    tags: latest-arm32v6
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: latest
    dockerfile: latest/Dockerfile.arm32v6
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: latest-arm32v6
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: arm64v8-latest

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: latest
    dockerfile: latest/Dockerfile.arm64v8
    dry_run: true
    repo: webhippie/unifi
    tags: latest-arm64v8
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: latest
    dockerfile: latest/Dockerfile.arm64v8
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: latest-arm64v8
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: manifest-latest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: latest/manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/master

depends_on:
- amd64-latest
- arm32v6-latest
- arm64v8-latest

---
kind: pipeline
name: amd64-5.10

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.10
    dockerfile: v5.10/Dockerfile.amd64
    dry_run: true
    repo: webhippie/unifi
    tags: 5.10-amd64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.10
    dockerfile: v5.10/Dockerfile.amd64
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: 5.10-amd64
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: arm32v6-5.10

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.10
    dockerfile: v5.10/Dockerfile.arm32v6
    dry_run: true
    repo: webhippie/unifi
    tags: 5.10-arm32v6
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.10
    dockerfile: v5.10/Dockerfile.arm32v6
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: 5.10-arm32v6
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: arm64v8-5.10

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.10
    dockerfile: v5.10/Dockerfile.arm64v8
    dry_run: true
    repo: webhippie/unifi
    tags: 5.10-arm64v8
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.10
    dockerfile: v5.10/Dockerfile.arm64v8
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: 5.10-arm64v8
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: manifest-5.10

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: v5.10/manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/master

depends_on:
- amd64-5.10
- arm32v6-5.10
- arm64v8-5.10

---
kind: pipeline
name: amd64-5.6

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.6
    dockerfile: v5.6/Dockerfile.amd64
    dry_run: true
    repo: webhippie/unifi
    tags: 5.6-amd64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.6
    dockerfile: v5.6/Dockerfile.amd64
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: 5.6-amd64
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: arm32v6-5.6

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.6
    dockerfile: v5.6/Dockerfile.arm32v6
    dry_run: true
    repo: webhippie/unifi
    tags: 5.6-arm32v6
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.6
    dockerfile: v5.6/Dockerfile.arm32v6
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: 5.6-arm32v6
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: arm64v8-5.6

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.6
    dockerfile: v5.6/Dockerfile.arm64v8
    dry_run: true
    repo: webhippie/unifi
    tags: 5.6-arm64v8
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    context: v5.6
    dockerfile: v5.6/Dockerfile.arm64v8
    password:
      from_secret: docker_password
    repo: webhippie/unifi
    tags: 5.6-arm64v8
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"

---
kind: pipeline
name: manifest-5.6

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: v5.6/manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/master

depends_on:
- amd64-5.6
- arm32v6-5.6
- arm64v8-5.6

---
kind: pipeline
name: microbadger-update

platform:
  os: linux
  arch: amd64

steps:
- name: microbadger
  pull: always
  image: plugins/webhook:1
  settings:
    url:
      from_secret: microbadger_url

trigger:
  ref:
  - refs/heads/master

depends_on:
- manifest-latest
- manifest-5.10
- manifest-5.6

...
