FROM ghcr.io/dockhippie/ubuntu:20.04-amd64@sha256:4f671531db85f083d5d991fe2133c83f17d28b3857199a39030947418301df2a

VOLUME ["/var/lib/unifi", "/var/log/unifi", "/var/run/unifi"]
EXPOSE 8080 8443

WORKDIR /var/lib/unifi
CMD ["/usr/bin/container"]

# mongodb got to be >= 2.4.10 and <= 4.0.0
RUN apt-get update && \
  apt-get upgrade -y && \
  groupadd -g 1000 unifi && \
  useradd -u 1000 -d /var/lib/unifi -g unifi -s /bin/bash -M unifi && \
  apt-get install -y binutils openjdk-8-jre-headless libcap2 jsvc mongodb-server && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN curl -sSL -o /tmp/unifi_sysvinit_all.deb https://dl.ui.com/unifi/6.2.17-ceb3ba714d/unifi_sysvinit_all.deb && \
  mkdir /tmp/unifi && \
  cd /tmp/unifi && \
  ar x /tmp/unifi_sysvinit_all.deb && \
  tar xf data.tar.xz && \
  cp -rf usr/lib/unifi /usr/lib/ && \
  rm -f /usr/lib/unifi/bin/mongod /usr/lib/unifi/bin/unifi.init && \
  ln -sf /usr/bin/mongod /usr/lib/unifi/bin/mongod && \
  rm -rf /tmp/unifi*

COPY ./overlay /
