FROM ghcr.io/dockhippie/ubuntu:20.04-arm64@sha256:8a106a7b8c0a04c98a511c4116d98c6a9c7193f1c4f96bad98314000b95d4565

VOLUME ["/var/lib/unifi", "/var/log/unifi", "/var/run/unifi"]
EXPOSE 8080 8443

WORKDIR /var/lib/unifi
CMD ["/usr/bin/container"]

# mongodb got to be >= 3.6.0 and <= 5.0.0
RUN apt-get update && \
  apt-get upgrade -y && \
  groupadd -g 1000 unifi && \
  useradd -u 1000 -d /var/lib/unifi -g unifi -s /bin/bash -M unifi && \
  apt-get install -y binutils openjdk-17-jre-headless libcap2 mongodb-server && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN curl -sSL -o /tmp/unifi_sysvinit_all.deb https://dl.ui.com/unifi/8.0.7/unifi_sysvinit_all.deb && \
  mkdir /tmp/unifi && \
  cd /tmp/unifi && \
  ar x /tmp/unifi_sysvinit_all.deb && \
  tar xf data.tar.xz && \
  cp -rf usr/lib/unifi /usr/lib/ && \
  rm -f /usr/lib/unifi/bin/mongod /usr/lib/unifi/bin/unifi.init && \
  ln -sf /usr/bin/mongod /usr/lib/unifi/bin/mongod && \
  rm -rf /tmp/unifi*

COPY ./overlay /
