FROM ghcr.io/dockhippie/ubuntu:20.04-amd64@sha256:e6a6ab74da744d8feac8d5d34137f7c835bea7b9c1ab6444274357c4e0b64e16

VOLUME ["/var/lib/unifi", "/var/log/unifi", "/var/run/unifi"]
EXPOSE 8080 8443

WORKDIR /var/lib/unifi
CMD ["/usr/bin/container"]

# mongodb got to be >= 2.6.0 and <= 4.0.0
RUN apt-get update && \
  apt-get upgrade -y && \
  groupadd -g 1000 unifi && \
  useradd -u 1000 -d /var/lib/unifi -g unifi -s /bin/bash -M unifi && \
  apt-get install -y binutils openjdk-11-jre-headless libcap2 mongodb-server && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN curl -sSL -o /tmp/unifi_sysvinit_all.deb https://dl.ubnt.com/unifi/7.4.162/unifi_sysvinit_all.deb && \
  mkdir /tmp/unifi && \
  cd /tmp/unifi && \
  ar x /tmp/unifi_sysvinit_all.deb && \
  tar xf data.tar.xz && \
  cp -rf usr/lib/unifi /usr/lib/ && \
  rm -f /usr/lib/unifi/bin/mongod /usr/lib/unifi/bin/unifi.init && \
  ln -sf /usr/bin/mongod /usr/lib/unifi/bin/mongod && \
  rm -rf /tmp/unifi*

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
