#!/bin/bash
source /usr/bin/entrypoint

echo "> creating data dir"
mkdir -p ${UNIFI_DATA_DIR}

echo "> symlink data dir"
ln -sf ${UNIFI_DATA_DIR} /usr/lib/unifi/data

echo "> creating log dir"
mkdir -p ${UNIFI_LOG_DIR}

echo "> symlink log dir"
ln -sf ${UNIFI_LOG_DIR} /usr/lib/unifi/logs

echo "> creating run dir"
mkdir -p ${UNIFI_RUN_DIR}

echo "> symlink run dir"
ln -sf ${UNIFI_RUN_DIR} /usr/lib/unifi/run

if [[ "${UNIFI_SKIP_CHOWN}" != "true" ]]
then
  echo "> chown data files"
  find ${UNIFI_DATA_DIR} \( \! -user unifi -o \! -group unifi \) -print0 | xargs -0 -r chown unifi:unifi

  echo "> chown log files"
  find ${UNIFI_LOG_DIR} \( \! -user unifi -o \! -group unifi \) -print0 | xargs -0 -r chown unifi:unifi

  echo "> chown run files"
  find ${UNIFI_RUN_DIR} \( \! -user unifi -o \! -group unifi \) -print0 | xargs -0 -r chown unifi:unifi
fi
